### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by stitch** [Bearle/django_mail_admin#17]
By no other means of reaching the author: thank you for this django plugin. It is nicely defined, does well what it should do and easy to understand. Thank you for not going all overboard in features and other stuff that's available elsewhere. Easily embedded into a project without fear :)

**Comment by delneg** [comment]
Thank you very much for those kind words.
Not very common to see something like that in OSS community.
It's great to know that this work is useful to someone even though i don't spend a lot of time maintaining this project nowadays.

**Comment by stitch** [comment]
You're welcome. :) We're using it in the internet.nl dashboard.

See you later!
