### ISSUE TITLE
cleanup_email management commad

### ISSUE THREAD

**Issue by AliPolat** [Bearle/django_mail_admin#2]
Hi,

* django mail admin version: 0.1.2
* Django version: 1.11.13
* Python version: 3.4
* Operating System: Windows 7

### Description

Wish  cleanup_email command deletes Incoming emails as well as Outgoing emails and their related attachments.

Thank You..

**Comment by delneg** [comment]
Please look at the commit mentioned above, I've implemented a feature that allows you to customize email deletion.

**Comment by delneg** [comment]
Released in 0.1.3
