### ISSUE TITLE
Question: Is there a planned release to support python 3.11?

### ISSUE THREAD

**Issue by girishkotra-alation** [Bearle/django_mail_admin#34]
* django mail admin version:
* Django version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Zagrebelin** [comment]
Supported since 0.3.2

**Comment by delneg** [comment]
Closing as done
