### ISSUE TITLE
Django 2.1+ support

### ISSUE THREAD

**Issue by JacoBezuidenhout** [Bearle/django_mail_admin#4]
* django mail admin version:
* Django version: 2.2b1
* Python version: 3.6
* Operating System: MacOS

### Description

I tried to add new outgoing email

### What I Did

I got the error:

render() got an unexpected keyword argument 'renderer'

** From Django 2.1: Support for Widget.render() methods without the renderer argument is removed.
https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1

**Comment by AliPolat** [comment]
django mail admin version: 0.1.3
Django version: 2.2.9
Python version: 3.6
Operating System: Windows

I have the exact same problem in my application.  I did understand the cause but no idea how to solve it.

**Comment by delneg** [comment]
Check 0.2.0
